# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlxgen < Formula
  desc "tool to generate sqlx models from schemas and queries"
  homepage "https://github.com/aakash-rajur/sqlxgen"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aakash-rajur/sqlxgen/releases/download/v1.0.0/sqlxgen_Darwin_arm64.tar.gz"
      sha256 "840d46b5871e193493c5e25e6ef5b40a2fc6ec6b519e010ce3fab081e0b1e19d"

      def install
        bin.install "sqlxgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aakash-rajur/sqlxgen/releases/download/v1.0.0/sqlxgen_Darwin_x86_64.tar.gz"
      sha256 "6f014b306e40fc9489e7f63d2c2475fd073ba1ec9c60282df16a991371c6400f"

      def install
        bin.install "sqlxgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aakash-rajur/sqlxgen/releases/download/v1.0.0/sqlxgen_Linux_x86_64.tar.gz"
      sha256 "b33df64ffa0312fb899ebcf511f9f67dfd8e9c4f25376dccc0081b50faba12d1"

      def install
        bin.install "sqlxgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aakash-rajur/sqlxgen/releases/download/v1.0.0/sqlxgen_Linux_arm64.tar.gz"
      sha256 "c225f155c7f83bdd32fb06711ab413553da3913909955efb35d88695495aadac"

      def install
        bin.install "sqlxgen"
      end
    end
  end

  test do
    system "#{bin}/sqlxgen version"
  end
end
