# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlxgen < Formula
  desc "tool to generate sqlx models from schemas and queries"
  homepage "https://github.com/aakash-rajur/sqlxgen"
  version "1.0.0-rc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aakash-rajur/sqlxgen/releases/download/v1.0.0-rc.1/sqlxgen_Darwin_arm64.tar.gz"
      sha256 "eb857ecc701010bfd1f3229e3b4bc6811099c31787392eb4c0a864dd0d600e73"

      def install
        bin.install "sqlxgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aakash-rajur/sqlxgen/releases/download/v1.0.0-rc.1/sqlxgen_Darwin_x86_64.tar.gz"
      sha256 "ad526c161db223abb4784a972a4436bf0bf2b4277241f21ed3011d999696c176"

      def install
        bin.install "sqlxgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aakash-rajur/sqlxgen/releases/download/v1.0.0-rc.1/sqlxgen_Linux_x86_64.tar.gz"
      sha256 "c8ce24bf1fd83af63a5435ce574ff9f926c394adea167d268804162b856380fd"

      def install
        bin.install "sqlxgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aakash-rajur/sqlxgen/releases/download/v1.0.0-rc.1/sqlxgen_Linux_arm64.tar.gz"
      sha256 "c0a8900afc64743593324f7aebfd57d32755cf704cfcd13c008006f309071618"

      def install
        bin.install "sqlxgen"
      end
    end
  end

  test do
    system "#{bin}/sqlxgen version"
  end
end
